const StumpConstants = {}
StumpConstants.titleTag = "titleTag"
StumpConstants.styleTag = "styleTag"
StumpConstants.tagMap = {}
StumpConstants.tagMap[StumpConstants.styleTag] = "style"
StumpConstants.tagMap[StumpConstants.titleTag] = "title"
StumpConstants.tags = {}
StumpConstants.tags.html = "html"
StumpConstants.tags.head = "head"
StumpConstants.tags.body = "body"
StumpConstants.collapseNode = "collapseNode"
StumpConstants.uidAttribute = "data-suid"
StumpConstants.class = "class"
StumpConstants.type = "type"
StumpConstants.value = "value"
StumpConstants.checkbox = "checkbox"
StumpConstants.checkedSelector = ":checked"
StumpConstants.contenteditable = "contenteditable"
StumpConstants.inputTypes = ["input", "div", "textarea"]

module.exports = StumpConstants
