import TreeNode from "../base/TreeNode";
import GrammarDefinitionErrorNode from "./GrammarDefinitionErrorNode";
import GrammarCustomConstructorNode from "./GrammarCustomConstructorNode";
import GrammarCompilerNode from "./GrammarCompilerNode";
import types from "../types";
declare abstract class AbstractGrammarDefinitionNode extends TreeNode {
    getKeywordMap(): {};
    getId(): string;
    protected _isNonTerminal(): boolean;
    _isAbstract(): boolean;
    protected _isAnyNode(): boolean;
    protected _getCustomDefinedConstructorNode(): GrammarCustomConstructorNode;
    private _cache_definedNodeConstructor;
    getDefinedConstructor(): any;
    protected _getDefaultNodeConstructor(): types.RunTimeNodeConstructor;
    protected _getDefinedNodeConstructor(): types.RunTimeNodeConstructor;
    getCatchAllNodeConstructor(line: any): typeof GrammarDefinitionErrorNode;
    getProgram(): TreeNode;
    getDefinitionCompilerNode(targetLanguage: any, node: any): GrammarCompilerNode;
    protected _getCompilerNodes(): GrammarCompilerNode[];
    getTargetExtension(): string;
    private _cache_keywordsMap;
    getRunTimeKeywordMap(): any;
    getRunTimeKeywordNames(): string[];
    getRunTimeKeywordMapWithDefinitions(): {};
    getNodeColumnTypes(): string[];
    protected _initKeywordsMapCache(): any;
    _getKeywordsInScope(): string[];
    getTopNodeTypes(): any[];
    protected _getKeywordsNode(): TreeNode;
    isRequired(): boolean;
    isSingle(): boolean;
    _getRunTimeCatchAllKeyword(): string;
    getKeywordDefinitionByName(keyword: string): any;
    protected _getCatchAllDefinition(): AbstractGrammarDefinitionNode;
    private _cache_catchAllConstructor;
    protected _initCatchAllNodeConstructorCache(): any;
    getAutocompleteWords(inputStr: any, additionalWords?: any[]): string[];
    isDefined(keyword: any): boolean;
    _getProgramKeywordDefinitionCache(): any;
    getRunTimeCatchAllNodeConstructor(): any;
}
export default AbstractGrammarDefinitionNode;
