# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy Scroll
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install and Build
        run: |
          npm install
          npm run buildDocs
          # Uncomment the line below if you are ignoring *.html files in your gitignore file
          rm .gitignore
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: wws # The branch the action should deploy to.
          folder: .
